### ISSUE TITLE
500  Server Error 

### ISSUE THREAD

**Issue by espery17** [benaja-bendo/bgr-dashboard-01#28]
quand je lance la commande '_php artisan serve_' , j'ai une **erreur 500.**
-par exemple sur la route : **http://127.0.0.1:8000/api/v1/students**

@benaja-bendo

**Comment by benaja-bendo** [comment]
As tu pensé à faire un `git pull`? Sur la branch dev

**Comment by espery17** [comment]
oui , je suis déjà sur la dernière version de la **branch dev**
