### ISSUE TITLE
Discusion sur le schéma BDD pour la partie cours

### ISSUE THREAD

**Issue by benaja-bendo** [benaja-bendo/bgr-dashboard-01#31]
À Partir des schémas de migrations du repos https://github.com/benaja-bendo/bgrfacile/tree/main/database/migrations proposer un schéma cohérent pour le stockage de cours.

**Comment by espery17** [comment]
Esquise d'un **schema** basé sur le model de [bgrFaclie](https://github.com/benaja-bendo/bgrfacile/blob/main/database/migrations/2023_06_11_184628_create_courses_table.php)


![Image](https://github.com/user-attachments/assets/5ec0a933-1c59-4e52-ab5e-fa0ef5d5e1dd)

**Comment by benaja-bendo** [comment]
> Esquise d'un **schema** basé sur le model de [bgrFaclie](https://github.com/benaja-bendo/bgrfacile/blob/main/database/migrations/2023_06_11_184628_create_courses_table.php)
> 
> ![Image](https://private-user-images.githubusercontent.com/93046318/354408356-5ec0a933-1c59-4e52-ab5e-fa0ef5d5e1dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTcyNzQsIm5iZiI6MTcyMjU5Njk3NCwicGF0aCI6Ii85MzA0NjMxOC8zNTQ0MDgzNTYtNWVjMGE5MzMtMWM1OS00ZTUyLWFiNWUtZmEwZWY1ZDVlMWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDExMDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZmI3NmE4YzVlYTAzOTkxNjgwMGIwMTk4YTcwYTc5MTJkYTRmMDk5ZDU0ZTNlNmYzMmFlZjZmMzAwZGUxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gymSAqDT6vMZ0U0o4ijTQ7jT0sEkQmJouCjL6wcVt8E)

les champs suivant ne sont pas dans le bon type:
- name -> varchar(255) de préférence
- course (et non coure_id) -> bigint de préférence

à la place de `content` mettre `description`. Le terme `content` sera reservé pour le contenu ou type de contenue que va prendre le cours.

**Comment by benaja-bendo** [comment]
En même temps, je te transfère le bon schéma à mon sens.

![Image](https://github.com/user-attachments/assets/24126712-3441-4579-bd3a-71eafa263972)

**Comment by espery17** [comment]
D'accord ça me vas , juste une question .
si on ne place pas le rubrique content directement dans la tables **courses** , à quel endroit tu pense la mettre ?
@benaja-bendo

**Comment by benaja-bendo** [comment]
@espery17 
Avec de la cardinalité `n:n` 

Un cours pourra avoir `n` contenus dans différents formats par exemple. 

- un contenu textuel avec une table `course_content_text` 
- un contenu visuel avec une table `course_content_image`
- etc.

Ce sera l'objet d'un autre ticket et d'une discussion avant implémentation.

**Comment by benaja-bendo** [comment]
Si tout est ok pour toi je te laisse close le ticket et prends le suivant

**Comment by espery17** [comment]
D'accord
