### ISSUE TITLE
Implémentation Api CRUD pour la ressource "course"

### ISSUE THREAD

**Issue by benaja-bendo** [benaja-bendo/bgr-dashboard-01#32]
Suite à l'échange sur le ticket #31.
Procédé à une implémentation CRUD des schémas retenu.

**Comment by espery17** [comment]
Je dois passé sur celui ci n'est ce pas ?
@benaja-bendo

**Comment by benaja-bendo** [comment]
@espery17 
Pour rappelle dans ta procédure:
1- définir la durée que tu estimes prendre pour le finir.
2- Mettre le ticket sur `inprogress`
3- crée une branch à partir de la branch `dev` ( pour les conventions de nommage de branch lire le commentaire suivant)
4- après solution ticket -> faire une **pull request vers dev** et me tags en reviewer 
5- une fois le ticket merge sur la dev il sera passé en Done.

**Comment by benaja-bendo** [comment]
Convention de nommage de branch:

## syntaxe

```sh
[type]/[issue-id]-[description]
```

## exemple

```sh
fix/123-fix-login-issue
```

## notes

**fix** : pour corriger un bug.
**feature** : pour ajouter une nouvelle fonctionnalité.
**hotfix** : pour des corrections urgentes.
etc.

## Bonnes pratiques 

- Utiliser des tirets (-) pour séparer les mots dans la description afin d'améliorer la lisibilité.

- Utiliser des noms de branches en minuscules pour éviter les erreurs de casse.

- Être concis mais descriptif : la description doit donner une idée claire de l'objet de la branche sans être trop longue.

**Comment by espery17** [comment]
pour la création de branch j'ai commit une erreur :
voici ce qui il ma proposé et j'ai valider : **32-implmentation-api-crud-pour-la-ressource-cours**
Est ce que ça va ou je dois le changé ?
@benaja-bendo

**Comment by benaja-bendo** [comment]
c'est pas grave.

**Comment by espery17** [comment]
J'ai terminer avec les crud des tables **courses** et **states_courses**.

lien : https://github.com/benaja-bendo/bgr-dashboard-01/tree/32-implmentation-api-crud-pour-la-ressource-cours

je veux juste savoir comment je peux faire pour faire la migration pour les BD des tenants déjà existant .

@benaja-bendo

**Comment by benaja-bendo** [comment]
> @espery17 
> Pour rappelle dans ta procédure:
> 1- définir la durée que tu estimes prendre pour le finir.
> 2- Mettre le ticket sur `inprogress`
> 3- crée une branch à partir de la branch `dev` ( pour les conventions de nommage de branch lire le commentaire suivant)
> 4- après solution ticket -> faire une **pull request vers dev** et me tags en reviewer 
> 5- une fois le ticket merge sur la dev il sera passé en Done.

@espery17 tu es actuellement à l'étage 4. Il te faut faire une PR et moi je te ferai un retour en review.

**Comment by espery17** [comment]
Une **PR** c'est quoi ?

**Comment by benaja-bendo** [comment]
@espery17 
Une pull request permet aux développeurs de notifier les autres membres de l'équipe qu'ils ont effectué des changements sur une branche de code et qu'ils souhaitent que ces changements soient examinés et, éventuellement, fusionnés dans la branche principale (ici "dev").

crée t'a PR ici:
https://github.com/benaja-bendo/bgr-dashboard-01/pulls
